version: '3.8'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anil-portfolio
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production
